# Generated by Django 3.2.8 on 2021-11-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сontract_time', models.DateTimeField()),
                ('Name_view', models.CharField(max_length=150)),
                ('percentage_of_insurance_premium', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_insurance', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.customer')),
                ('employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.employeer')),
                ('type_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.typeofinsurance')),
            ],
        ),
    ]
