# Generated by Django 3.2.8 on 2021-11-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_dogovor_typeofinsurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofinsurance',
            name='сontract_time',
            field=models.CharField(max_length=10),
        ),
    ]
