# Generated by Django 3.2.8 on 2021-11-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_typeofinsurance_сontract_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_opinion', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Заключение врача')),
                ('customer_request', models.TextField(blank=True, verbose_name='Заявление клиента')),
                ('approved', models.BooleanField(default=True, verbose_name='Одобрено')),
                ('dogovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.dogovor', verbose_name='Номер договора')),
            ],
        ),
    ]
