# Generated by Django 3.2.8 on 2021-11-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_applicationforpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='sum_insurance',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_pay', models.DecimalField(decimal_places=3, max_digits=20)),
                ('transfer_account', models.CharField(max_length=150)),
                ('applicationForPayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.applicationforpayment', verbose_name='Номер заявки')),
            ],
        ),
    ]
