# Generated by Django 3.2.8 on 2021-11-16 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='typeofinsurance',
            name='сontract_time',
            field=models.DateTimeField(),
        ),
    ]
