# Generated by Django 3.2.8 on 2021-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20211116_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='sum_insurance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
