# Generated by Django 3.2.8 on 2021-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_payment_sum_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofinsurance',
            name='percentage_of_insurance_premium',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
