# Generated by Django 3.2.8 on 2021-12-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_alter_typeofinsurance_percentage_of_insurance_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profile',
            field=models.ImageField(default='', upload_to='photos_profile/%Y/%m/%d', verbose_name='Фото профиля'),
            preserve_default=False,
        ),
    ]
