# Generated by Django 3.2.8 on 2021-12-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_alter_user_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofinsurance',
            name='Description_view',
            field=models.TextField(blank=True),
        ),
    ]
